config/routes.rb
Rails.application.routes.draw do
  root                'videos#index'
  get    'home'    => 'dynamic_pages#home'
  get    'artist'  => 'dynamic_pages#artist'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  
  resources :users

  resources :videos do
    collection do
      get 'search'
    end
    resources :videos, only: [:index, :new, :create]
  end
  
end

app/models/video.rb
# == Schema Information
#
# Table name: videos
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  link       :string(255)
#  uid        :string(255)
#  author     :string(255)
#  duration   :string(255)
#  likes      :string
#  dislikes   :string
#  views      :string

class Video < ActiveRecord::Base
  searchkick

  YT_LINK_FORMAT = /\A.*(youtu.be\/|v\/|u\/\w\/|embed\/|watch\?v=|\&v=)([^#\&\?]*).*\z/i
  validates :link, presence: true, format: YT_LINK_FORMAT

  before_create -> do
    uid = link.match(YT_LINK_FORMAT)

    self.uid = uid[2] if uid && uid[2]

    if self.uid.to_s.length != 11
      self.errors.add(:link, 'is invalid.')
      false
    elsif Video.where(uid: self.uid).any?
      self.errors.add(:link, 'is not unique.')
      false
    else
      get_additional_info
    end
  end

private
 
  def get_additional_info
    begin
      client = YouTubeIt::OAuth2Client.new(dev_key: ENV['YT_DEV'])
      video  = client.video_by(uid)
      self.title    = video.title
      self.duration = parse_duration(video.duration)
      self.author   = video.author.name
      self.likes    = parse_count(video.rating.likes)
      self.dislikes = parse_count(video.rating.dislikes)
      self.views    = parse_count(video.view_count)
    rescue
      self.title = '' ; self.duration = '00:00' ; self.author = '' ; 
      self.likes = '0' ; self.dislikes = '0' ; self.views = '0'
    end
  end
   
  def parse_duration(d)
    hr  = (d / 3600).floor
    min = ((d - (hr * 3600)) / 60).floor
    sec = (d - (hr * 3600) - (min * 60)).floor
   
    hr  = '0' + hr.to_s  if hr.to_i  < 10
    min = '0' + min.to_s if min.to_i < 10
    sec = '0' + sec.to_s if sec.to_i < 10
   
    if hr == '00'
      min.to_s + ':' + sec.to_s
    else
      hr.to_s + ':' + min.to_s + ':' + sec.to_s
    end
  end

  def parse_count(num)
    str = num.to_s
    if str.length <= 6
      parse = str.reverse.scan(/.{1,3}/).join(',').reverse
    elsif str.length > 6
      if (num % 1000000) < 5000
        str = (num / 1000000).to_s
      else
        str = (num.to_f / 1000000.to_f).round(2).to_s 
      end
      parse = str  + " mil"
    end
    
    parse
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
 
  def index
    @videos = Video.order('created_at DESC').paginate(page: params[:page], per_page: 15)
  end

  def new
    @video = Video.new
  end
   
  def create
    @video = Video.new(params.require(:video).permit(:link))
    if @video.save
      flash[:success] = 'Video added!'
      redirect_to root_url
    else
      render 'new'
    end
  end

  def search
    if params[:search].present?
      @videos = Video.search(params[:search])
    else
      @videos = Video.order('created_at DESC').paginate(page: params[:page], per_page: 15)
    end
  end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_jumbotron.html.erb
<div class="jumbotron">
  <div class="container">
    <h1w><b>GOOD MUSIC IS GOOD MUSIC.</b></h1w>
    <p><b>If you know an artist who deserves musical recognition, let's share their music and expose their talent. The only thing that can happen overnight is recognition. The talent was always in us.</b></p> 
    <br>
    <p1>
      <%= link_to 'Share music!', new_video_path, class: 'btn btn-primary btn-lg', 
                                                  id:'btnShadow' %>
    </p1>
  </div>
</div>

app/views/videos/_videos.html.erb
<div class="col-md-4">
  <div class="yt_video thumbnail">
    <a href="#">
      <%= link_to video.link do %> 
        <%= image_tag "https://img.youtube.com/vi/#{video.uid}/mqdefault.jpg", alt: video.title,             class: 'yt_preview img-rounded', :"data-uid" => video.uid %> 
      <% end %>
    </a>
    <h5><span class="highlightme"><%= video.duration %></span></h5>
    <div class="caption">
      <div class="text_overflow">
        <a href="#">
          <h3>
            <%= link_to video.title, root_path(anchor: "player-wrapper"), 
                                     class: "yt_preview videolink", :"data-uid" => video.uid %>
          </h3>
        </a>
      </div>
      <h4>Artist: <b><%= video.author %></b></h4>
        <h4>
          <span class="glyphicon glyphicon-eye-open"></span> 
            <%= video.views %>
          <div class="pull-right">
            <span class="glyphicon glyphicon glyphicon-thumbs-up"></span> 
              <%= video.likes %>
            <span class="glyphicon glyphicon glyphicon-thumbs-down"></span> 
              <%= video.dislikes %>
          </div>
        </h4>
    </div>
  </div>
</div>

app/views/videos/index.html.erb
<% provide(:title, "A Hub Of Cover Songs From Talented Artists Who Deserve Musical Recognition") %>

<%= render 'jumbotron' %>

<% if @videos.any? %>
  <div class="container-fluid">
    <h1>Trending videos</h1>
 
    <div id="player-wrapper"></div>
    <br></br>
    <%= will_paginate %>
    <% @videos.in_groups_of(3) do |group| %>
      <div class="row">
        <% group.each do |video| %>
          <% if video %>
            <%= render 'videos', video: video %>
          <% end %>
        <% end %>
      </div>
    <% end %>
    <%= will_paginate %>
  </div>
<% end %>

app/views/videos/new.html.erb
<% provide(:title, 'New Video') %>

<h1>New video</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@video) do |f| %>
    
      <%= render 'shared/error_messages', object: @video %>

      <div class="form-group">
        <%= f.label :link %>
        <%= f.text_field :link, class: 'form-control', required: true %>
        <span class="help-block">A link to the video on YouTube.</span>
      </div>

      <%= f.submit "Upload video", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/videos/search.html.erb
<% provide(:title, "A Hub Of Cover Songs From Talented Artists Who Deserve Musical Recognition") %>

<%= render 'jumbotron' %>

<% if @videos.any? %>
  <div class="container-fluid">
    <h1>Trending videos</h1>
 
    <div id="player-wrapper"></div>
    <br></br>
    <%= will_paginate %>
      <div class="row">
        <% @videos.each do |video| %>
          <% if video %>
            <%= render 'videos', video: video %>
          <% end %>
        <% end %>
      </div>
    <%= will_paginate %>
  </div>
<% end %>