config/routes.rb
Rails.application.routes.draw do
  root                'videos#index'
  get    'home'    => 'dynamic_pages#home'
  get    'artist'  => 'dynamic_pages#artist'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  
  resources :users

  resources :videos do
    collection do
      get 'search'
    end
    resources :videos, only: [:index, :new, :create]
  end
  
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>© 2015 | Created by Tambino</small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "MusicalRec", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-left">
        <li><%= link_to "Home",      root_path %></li>
        <li><%= link_to "Artists",   artist_path %></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li>
          <div style="display:inline">
            <%= form_tag search_videos_path, method: :get, class: "form-inline", 
                                             role: "search" do %> 
              <div class="form-group">
                <%= text_field_tag :search, params[:search], class: "form-control", 
                                           id: "searchForm", placeholder: "Search" %>
              </div>
              <%= button_tag(type: "submit", class: "btn btn-default", 
                                         id: "searchButton") do %>
                <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
              <% end %>
            <% end %>   
          </div>      
        </li>
        <li><%= link_to "About Us",  about_path %></li>
        <li><%= link_to "Contact",   contact_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <span class="glyphicon glyphicon-user" aria-hidden="true"></span> 
              <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript" src="https://www.youtube.com/iframe_api"></script>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>